version: ‘3’

services:

  mariadb:
    build:
      context: requirements/mariadb
      args:
        NAME: ${DB}
        USER: ${DB_USER}
        PASSWORD: ${DB_PASSWORD}
    container_name: mariadb
    env_file: .env
    networks:
      - Docker network
    restart: unless-stopped
    volumes:
      - DB:/var/lib/mysql

  wordpress:
    build:
      context: requirements/wordpress
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - Docker network
    restart: on-failure
    volumes:
      - wordpress:/var/www/wordpress

  nginx:
    build:
      context: requirements/nginx
      args:
        DOMAIN: ${DOMAIN_NAME}
    container_name: nginx
    env_file: .env
    depends_on:
      - wordpress
    networks:
      - Docker network
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - wordpress:/var/www/wordpress

volumes:

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/zharzi/data/wordpress

  DB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/zharzi/data/DB

networks:
  Docker network:
    driver: bridge
